### PR TITLE
Drop support for PHP 7.4 & run tests on PHP 8.2

### PR DESCRIPTION
**Pull request by nbayramberdiyev**
This PR drops support for PHP 7.4 and allows to run tests on PHP 8.2.

### CODE REVIEW

**Comment by freekmurze** [comment]
Why was 7.4 dropped? Can't we just add 8.2?

**Comment by nbayramberdiyev** [comment]
Because 7.4 has reached its end of life. Should I revert it?

**Comment by freekmurze** [comment]
Yeah, let's just add 8.2 for now.

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
